### ISSUE TITLE
error object has no attribute 'get_sync_data'

### ISSUE THREAD

**Issue by amon-ra** [akretion/angular-odoo#12]
I am testing your module but I cannot understand the attribute get_sync_data. Needs a module to be installed on Odoo server in order to work?

**Comment by lucasdiedrich** [comment]
@amon-ra , i really recommend that you use this instead: https://github.com/hparfr/angular-odoo

At least, until akretion merge @hparfr full work here.

**Comment by amon-ra** [comment]
The code from  @hparfr is merged in develop branch, the error in server is the same.
I have missing the attribute get_sync_data in server

**Comment by hparfr** [comment]
get_sync_data  (odoo side) is here https://github.com/akretion/synchronizer/blob/7.0/synchronizer/model.py#L111 (it should work on v7 and v8).

**Comment by amon-ra** [comment]
thanks!
